### PR TITLE
Fix: `CopyTo` provided with other types overloads

### LINKED ISSUE #11: `CopyTo()` is missing other types overloads
The `CopyTo()` method allows to copy the `Vector<T>` elements into an array, but all implementations allows only to copy the elements into raw array given as buffer's pointer.

Most often there are other types used by C++ developers (`std::vector`, `std::array`).
These types should be handled as well.

---

The documentation shouldn't be a big problem. It will be kept the same as for other overloads, but the array size shouldn;t be necessary.

### PR DESCRIPTION
**Pull request by BartoszKlonowski**
This pull request fixes #11 

It provides the `CopyTo()` method with additional container types overloads such as: `std::array` and `std::vector`

---

The implementation is very basic:
It overloads and adapts the original raw pointer oriented overload and uses the given type under the hood.

Unit tests checks the same scenarios as for the raw pointer method, but in addition they are extended with correct insertion cases, where part of original sequence is moved by given offset.

This pull request also adjusts the README documentation regarding the dependencies - *array* header had to be included so the `std::array` can be supported.

### CODE REVIEW

File: Source/Vector.hpp [hunk 1]
```diff
@@ -205,6 +206,81 @@ namespace Cx
...
+        /// <param name="array">The std::vector that is the destination of the elements copied from Vector</param>
+        template<std::size_t size>
+        void CopyTo( std::array<T, size>& array )
+        {
+            for( unsigned int i = 0; i < this->size(); ++i )
+                array[i] = this->at( i );
+        }
+
+        /// <summary>
+        /// Copies the entire Vector to a compatible std::vector, starting at the specified index of the target array
```
Comment (BartoszKlonowski) [inline Source/Vector.hpp]: std::vector - copy-paste mistake. Should be std::array

**Review by BartoszKlonowski — COMMENTED** [review]
This comment applies to all `std::array` overloads.
